# Site settings
title: Brenda <span class="ruby">Ruby</span>
email: bvbren@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Brenda <span class="ruby">Ruby's</span> Photograpy and Blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bvbren.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
